logging:
    level:
        org:
            springframework:
                web:
                    filter: debug
server:
    port: 8087
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: lesm1serab1e
        url: jdbc:mysql://relearn.cqaoehsuwhpj.ap-northeast-2.rds.amazonaws.com:3306/study
        username: relearn
    mvc:
        hiddenmethod:
            filter:
                enabled: true
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
